behaviors:
  Maze_Raycasts_Grid:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128          # Larger batch size for better gradient estimates
      buffer_size: 512         # Buffer size 4x batch size for diverse experience replay
      learning_rate: 1.0e-4    # Lower learning rate for stability
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95              # Slightly lower lambda for balancing bias and variance
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true          # Enable normalization for observation scaling
      hidden_units: 256        # Larger network for better generalization
      num_layers: 3            # Increase depth for complex policies
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 50000000
    time_horizon: 128          # Increased to allow learning longer-term dependencies
    summary_freq: 2000         # More frequent logging for monitoring
